version: '3.6'
services:
  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mail-queue
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

