spring:
  profiles.active: @spring.profile@

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mail-queue?characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
    username: root
    test-on-borrow: true
    validateion-query: select 1

  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        globally_quoted_identifiers: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: @gmail.username@
    password: @gmail.password@
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

logging.level:
  ROOT: DEBUG
  org.hibernate.SQL: INFO
