spring:
  profiles.active: @spring.profile@

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mail-queue
    username: root
    password: root

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        hbm2ddl.auto: update
        globally_quoted_identifiers: true

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: @gmail.username@
    password: @gmail.password@
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

logging.level:
  ROOT: INFO
  org.hibernate.SQL: DEBUG
